### ISSUE TITLE
PhantomJS leg doesn't work

### ISSUE THREAD

**Issue by tsypa** [gpolitis/node-tarantula#24]
./example-wikidive-phantom.js
Crawling…  http://en.wikipedia.org/
phantom.create http://en.wikipedia.org/ from undefined
done
## 

no output from uris and request events as expected

**Comment by robcolburn** [comment]
Thanks, we do need to improve those error messages.  It sounds like it's having an issue connecting to PhantomJS.
- Have you installed PhantomJS? (remember it's a separate download & installation).
- Which platform are you on? (Mac, Win, Linux). I haven't done any testing against Win.

If you'd like to get in and debug, I'd tracing around this line.

https://github.com/gpolitis/node-tarantula/blob/master/lib/client/PhantomClient.js#L103

**Comment by tsypa** [comment]
phantomjs installed via apt-get and works (I use it with casperjs)  
phantomjs -v
1.9.7

Platform is Linux (Lubuntu 13.10)
How can I debug ? no errors from example-wikidive-phantom.js

**Comment by robcolburn** [comment]
Just before line 137, add in:

``` js
console.log(err);
console.log(page);
```

In the PhantomClient.js
https://github.com/gpolitis/node-tarantula/blob/master/lib/client/PhantomClient.js#L103

That should provide a little more visibility to the issue.

**Comment by tsypa** [comment]
After reboot machine, example-wikidive-phantom.js works %)
I kept the extra logging in case of repetition of the error
I run example-wikidive-phantom.js and got error

Error executing command to extract phantom ports: Error: Command failed: warning, got bogus unix line.

Then I started again and got error from phantom
phantom stderr: pure virtual method called

phantom stderr: terminate called without an active exception

phantom stderr: PhantomJS has crashed. Please read the crash reporting guide at https://github.com/ariya/phantomjs/wiki/Crash-Reporting and file a bug report at https://github.com/ariya/phantomjs/issues/new with the crash dump file attached: /tmp/7fb52dd1-d477-da7b-50bd892f-134901e0.dmp

**Comment by tsypa** [comment]
I install phantomjs on other machine with debian 7, then add console.log(err)
in PhantomClient.prototype._get in page.includeJS callback

``` javascript
page.includeJs('//ajax.googleapis.com/ajax/libs/jquery/2.0.3/jquery.min.js', function (err) {
                                if (err) {
                                        console.log('E: ' + err);
                                        return thisClient.emit('error', 'phatom.page.includeJs', err);
                                }

```

Then I run example-wikidive-phantom.js abd run ./example-wikidive-phantom.js and got next error

``` sh
./example-wikidive-phantom.js
     Crawling…  http://en.wikipedia.org/
GET http://en.wikipedia.org/
E: No response body for page.includeJs()
phatom.page.includeJs http://en.wikipedia.org/ from undefined
done

```

**Comment by robcolburn** [comment]
Seems like there's a breakdown in the bridge to phantom, we'll likely need a patch in the [node-phantom-simple module](https://www.npmjs.org/package/node-phantom-simple).

I do see similar [issues with that module](https://github.com/baudehlo/node-phantom-simple/issues).

Tarantula in phantom mode is really just a thin abstraction on that module.

**Comment by robcolburn** [comment]
Updated dependencies and error docs, hopefully that helps.
